### ISSUE TITLE
Resetting default global tuning

### ISSUE THREAD

**Issue by biophony** [Ixox/preenfm3#53]
Not necessarily an issue, but is there a way to set the default global tuning to 440.0? Oddly, my synth is set by default to 4.33. I have to remember to adjust it every time I boot up, but I was wondering if it were possible to set 440 as default?

**Comment by pvig** [comment]
Yes, there is an easy way :
set tuning on Mix > Global > Tuning
with Menu > Mixer > Defl > Save ,
your tuning is saved as default value on boot.

**Comment by biophony** [comment]
Thanks!
